### PR TITLE
Enable async processing of messages

### PR DESCRIPTION
**Pull request by alexandre-normand**
## What is this about
This intends to address the use-case described by @pmcintyresfdc in issue #145. 

This is still a big rough and I'll be pushing updates in the coming days but wanted to get something out to show you, @pmcintyresfdc. 

TODO: 
 * [x] Move hashing-related functions and write missing table tests for those. 
 * [x] Review the godoc to make sure it's clear enough to users that might want to play with this advanced configuration. 
 * [x]  I'd also like to comment on the main test that proves this works since it might not be obvious to me or others what's going on if we ever have to revisit later.
 * [x] Add some timeout to the new test since someone that would break the parallel processing of messages would end up having that test hang and that wouldn't be easy to troubleshoot if I'm not providing a descriptive error message. 

That said, I have that good robust test that makes me feel confident with this implementation. 

And thanks to @coderunner for having inspired the partition hashing scheme from previous work done together. I think this nice feature doesn't look too bad as far as maintenance cost goes. 

### Checklist
*   [x] I've reviewed my own code
*   [x] I've executed `go build ./...` and confirmed the build passes
*   [x] I've run `go test ./...` and confirmed the tests pass

### CODE REVIEW

**Comment by alexandre-normand** [comment]
@pmcintyresfdc: I think I'm done with all the things I wanted to do for this one. Since you made the initial request, do you mind trying this out and confirming this works for your use case? I think the default advanced configurations should be sufficient so you'd just have to build using the latest commit on this branch:
`go get gitHub.com/alexandre-normand/slackscot@ 2cb82b3fcad594b338ace8cb3571c4cae634e6df`. 

Thanks 🙇

**Comment by pmcintyresfdc** [comment]
Works great! Although I should point out that I had to add the advanced.* configuration items to my config. But that's because I'm using a viper instance from a parent and not one based on config.NewViperWithDefaults. Thanks!

PS Sorry for disappearing - got super busy with some ops work.

**Comment by alexandre-normand** [comment]
> Although I should point out that I had to add the advanced.* configuration items to my config. But that's because I'm using a viper instance from a parent and not one based on config.NewViperWithDefaults

Thanks for noting that. I think I should just have the viper defaults be global ones to avoid exactly this. I'll add this soon.

**Comment by pmcintyresfdc** [comment]
No problem! Sounds like a good fix.

**Comment by pmcintyresfdc** [comment]
Maybe you could make it so that defaults function gets called on any viper passed into the NewBot

**Pull request merged**
