### PR TITLE
Switched to slack-go/slack rather than nlopes old repo

### PR DESCRIPTION
**Pull request by pmcintyresfdc**
## What is this about
Using the new slack-go/slack repo

### Checklist
*   [x] I've reviewed my own code
*   [x] I've executed `go build ./...` and confirmed the build passes
*   [x] I've run `go test ./...` and confirmed the tests pass

### CODE REVIEW

**Comment by alexandre-normand** [comment]
Thanks, @pmcintyresfdc! 

Can you run a `go mod tidy` and `go build`? I would expect `go.mod` and `go.sum` to have some changes.

**Comment by pmcintyresfdc** [comment]
Hey, I ran both of those before commit. Re-ran with no changes.

**Comment by pmcintyresfdc** [comment]
And both of those files did have changes

**Comment by alexandre-normand** [comment]
Oh right. Sorry I missed that.

**Comment by alexandre-normand** [comment]
Thanks again, @pmcintyresfdc . Released as `v1.43.0`.

**Pull request merged**
